package kgen.rust

enum class ModuleType {
    Directory,
    FileModule,
    /// For modules that are generated by other systems, like proto buf generated modules.
    PlaceholderModule,
    Inline
}