package kgen.rust

/**
 * Represents the type of a module, defining its structure and origin.
 */
enum class ModuleType {
    /**
     * A directory module, typically containing other files or modules.
     */
    Directory,

    /**
     * A file-based module, representing a single file as the module.
     */
    FileModule,

    /**
     * A placeholder module, used for modules generated by external systems,
     * such as Protocol Buffers or other code generation tools.
     */
    PlaceholderModule,

    /**
     * An inline module, defined directly within another structure or file.
     */
    Inline
}
