name: Tests for Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run-file:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Compile Rust file
      run: rustc temp/kgen_db/src/sample.rs
      
    - name: Run Rust file
      run: ./sample
