name: Tests for Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run-file:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Checkout
    - uses: actions/checkout@v4
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Run Test File
      run: |
        rustc temp/kgen_db/src/sample.rs
        ./sample
